version: '3'

services:

    elasticsearch:

        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: es
        ports:

            - '9200:9200'

           
    kibana:

        image: docker.elastic.co/kibana/kibana:7.6.2
        container_name: kb
        ports:

            - '5601:5601'

        depends_on:

            -  elasticsearch

    
