version: "3"
networks:
  discoveryserver: 
services:
  discoveryserver:
    build: ./discoveryserver
    image: sdkanse/discoveryserver:0.0.1-SNAPSHOT.jar
    container_name: server
    ports:
      - "8001:8000"
    networks:
      - discoveryserver
   

  hrd-emp-be:
    build: ./hrd-emp-be
    image: sdkanse/hrd-emp-be:0.0.1-SNAPSHOT.jar
    container_name: be
    ports:
      - "8084:8083"
    networks:
      - discoveryserver
    depends_on:
      - discoveryserver
 

  hrd-emp-fe:
    build: ./hrd-emp-fe
    image: sdkanse/hrd-emp-fe:0.0.1-SNAPSHOT.jar
    container_name: fe
    ports:
      - "8081:8082"
    networks:
      - discoveryserver
    depends_on:
      - hrd-emp-be
      - discoveryserver
 

