spring:
  application:
    name: hrd-emp-fe
    
server:
  port: 8082    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
         
         
         
         
          