FROM docker.elastic.co/elasticsearch/elasticsearch:7.6.2
# copy the configuration file into the container
COPY elasticsearch.yml /usr/share/elasticsearch/config

# expose the default Elasticsearch port
EXPOSE 9200
